{
 "title": "Liberando Productos Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Server total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "server_requests_total{container=\"python-app\"}"
    }
   ]
  },
  {
   "title": "Main endpoint requests number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "main_requests_total{container=\"python-app\"}"
    }
   ]
  },
  {
   "title": "Health endpoint requests number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "healthcheck_requests_total{container=\"python-app\"}"
    }
   ]
  },
  {
   "title": "Bye endpoint requests number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "bye_requests_total{container=\"python-app\"}"
    }
   ]
  },
  {
   "title": "App total restarts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{container=\"python-app\"}"
    }
   ]
  }
 ]
}