apiVersion: v1
kind: Service
metadata:
  name: "{{ include "spring-app.fullname" . }}-db"
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.db.servicePort }}
  clusterIP: None
  selector:
    {{- include "spring-app.selectorLabels" . | nindent 4 }}
    layer: database
