apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "spring-app.fullname" . }}-secrets"
type: Opaque
data:
  {{- if not .Values.db.user }}
  mariadb-user: {{ randAlpha 8 | b64enc | quote }}
  {{- else }}
  mariadb-user: {{ .Values.db.user | quote }}
  {{- end }}
  
  {{- if not .Values.db.password }}
  mariadb-password: {{ randAlphaNum 15 | b64enc | quote }}
  {{- else }}
  mariadb-password: {{ .Values.db.password | quote }}
  {{- end }}
  
  {{- if not .Values.db.rootPassword }}
  mariadb-root-password: {{ randAlphaNum 15 | b64enc | quote }}
  {{- else }}
  mariadb-root-password: {{ .Values.db.rootPassword | quote }}
  {{- end }}
