apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "spring-app.fullname" . }}-configmap"
data:
  DB_HOST: "{{ include "spring-app.fullname" . }}-db" 
  DB_PORT: "{{ .Values.db.servicePort }}"
  DB_SCHEMA: {{ .Values.db.name | quote }}

